"resource/ui/hudammoweapons.res"
{
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"	"HudWeaponAmmoBG"
		"xpos"	"9999"
		"visible"	"0"
		"enabled"	"0"
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"HudWeaponLowAmmoImage"
		"xpos"	"9999"
		"visible"	"0"
		"enabled"	"0"
	}
	"AmmoBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"AmmoBG"
		"xpos"	"9999"
		"ypos"	"0"
		"zpos"	"1"
		"wide"	"110"
		"tall"	"43"
		"visible"	"0"
		"enabled"	"0"
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"AmmoInClip"
		"font"	"FontBold50"
		"xpos"	"9999"
		"ypos"	"0"
		"zpos"	"5"
		"wide"	"65"
		"tall"	"43"
		"visible"	"0"
		"enabled"	"0"
		"textAlignment"	"east"
		"labelText"	"%Ammo%"
	}
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"AmmoInClipShadow"
		"font"	"ScanlineShadow"
		"fgcolor"	"Black"
		"xpos"	"9999"
		"ypos"	"-2"
		"zpos"	"5"
		"wide"	"65"
		"tall"	"43"
		"visible"	"0"
		"enabled"	"0"
		"textAlignment"	"east"
		"labelText"	"%Ammo%"
	}
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"AmmoInReserve"
		"font"	"FontBold22"
		"xpos"	"9999"
		"ypos"	"0"
		"zpos"	"7"
		"wide"	"f0"
		"tall"	"43"
		"visible"	"0"
		"enabled"	"0"
		"textAlignment"	"west"
		"labelText"	"%AmmoInReserve%"
	}
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"AmmoInReserveShadow"
		"font"	"ScanlineShadowSmall"
		"fgcolor"	"Black"
		"xpos"	"9999"
		"ypos"	"-2"
		"zpos"	"7"
		"wide"	"f0"
		"tall"	"43"
		"visible"	"0"
		"enabled"	"0"
		"textAlignment"	"west"
		"labelText"	"%AmmoInReserve%"
	}
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"AmmoNoClip"
		"font"	"FontBold50"
		"xpos"	"9999"
		"ypos"	"0"
		"zpos"	"5"
		"wide"	"110"
		"tall"	"43"
		"visible"	"0"
		"enabled"	"0"
		"textAlignment"	"center"
		"labelText"	"%Ammo%"
	}
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"AmmoNoClipShadow"
		"font"	"ScanlineShadow"
		"fgcolor"	"Black"
		"xpos"	"9999"
		"ypos"	"-2"
		"zpos"	"5"
		"wide"	"110"
		"tall"	"43"
		"visible"	"0"
		"enabled"	"0"
		"textAlignment"	"center"
		"labelText"	"%Ammo%"
	}
}
